### ISSUE TITLE
Error printing process exit code

### ISSUE THREAD

**Issue by jessealama** [Bogdanp/racket-chief#1]
While working with a koyo app I set up a one-line Procfile

````
web: raco koyo serve
````

which ran just fine with `raco chief start`. After a while, I sent Ctrl-C in the terminal, I got this:

````
zero?: contract violation
  expected: number?
  given: #f
  context...:
   /usr/local/share/racket/pkgs/chief/private/formation.rkt:150:0: ~c
   /usr/local/share/racket/pkgs/chief/private/formation.rkt:64:2: event-loop
   /usr/local/share/racket/collects/racket/private/more-scheme.rkt:163:2: select-handler/no-breaks
   body of "/usr/local/share/racket/pkgs/chief/cli.rkt"
   /usr/local/share/racket/collects/raco/raco.rkt:41:0
   body of "/usr/local/share/racket/collects/raco/raco.rkt"
   body of "/usr/local/share/racket/collects/raco/main.rkt"
````

followed by a (non-clean) exit.

FWIW this was on FreeBSD 13.0. Not sure if the architecture might be playing a role.

**Comment by Bogdanp** [comment]
Thanks for the report! I don't have a working FreeBSD VM to test with right now, but I suspect https://github.com/Bogdanp/racket-chief/pull/2 will fix the issue or at least uncover some other problem. Can you give it a try?

**Comment by jessealama** [comment]
Looks like a plausible solution! (I should have added that this error doesn't happen every time I manually kill the chief process. Just sometimes.)

**Comment by Bogdanp** [comment]
Ah, I see; I thought it was reproducible. In any case, I've merged the change. If it happens again, I can take a deeper look.
